#index:
#    path: /
#    controller: Forum9000\Controller\DefaultController::index

f9kuser_logout:
    path: /logout

default:
    path: /{path_alias}
    controller: Forum9000\Controller\DefaultController::handle_alias
    requirements:
        path_alias: ".+"