doctrine_migrations:
    dir_name: '%kernel.project_dir%/core/Migrations'
    # namespace is arbitrary but should be different from Forum9000\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
